apiVersion: v1
kind: Pod
metadata:
  name: vect-add
spec:
  hostIPC: true
  restartPolicy: OnFailure
  securityContext:
    runAsUser: 1000
  containers:
  - name: vect-add
    image: "xzaviourr/vect_add:v1.2"
    imagePullPolicy: Never
    resources:
      requests:
        nvidia.com/vcore: 20
        nvidia.com/vmem: 4
      limits:         
        nvidia.com/vcore: 20
        nvidia.com/vmem: 4